# Workflow to Terratest the Terraform Modules

name: Terratest VPC & Web Modules

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-2

jobs:
  tests:
    name: Terratest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Initialise Go Modules
        run: go mod init test
        working-directory: tests

      - name: Install Dependencies
        run: go mod tidy
        working-directory: tests

      - name: Terratesting Modules
        run: go test -v modules_test.go
        working-directory: tests